#!/usr/bin/env python3
"""
AI Threat Intelligence Report Generator
Uses Anthropic API with web search to research and generate weekly reports.
Runs via GitHub Actions on a weekly schedule.
"""

import anthropic
import os
import re
from datetime import datetime, timedelta

def generate_report():
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    today = datetime.now().strftime("%Y-%m-%d")
    week_ago = (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d")
    year = datetime.now().strftime("%Y")

    prompt = f"""You are an AI security threat intelligence analyst. Today is {today}.

Research the latest AI and LLM security incidents, vulnerabilities, and threats from the past week ({week_ago} to {today}).

Use web search to find REAL, current events. Do NOT make up incidents.

Write a structured threat intelligence report in markdown with these sections:

# AI Threat Intelligence Report — Week of {today}

## Summary
2-3 sentence executive summary of the week's key findings.

## Critical Incidents
For each real incident found (up to 5):
### [Incident Name]
- **Date:** when it happened
- **Category:** Supply Chain / LLM Vulnerability / Model Security / AI Infrastructure / Regulatory
- **Impact:** who was affected and how
- **Technical Details:** what happened technically (2-3 sentences)
- **Detection:** how it was or could be detected
- **Mitigation:** recommended response

## Emerging Threats
Brief paragraph on 2-3 emerging trends or threats that haven't materialized yet but are worth watching.

## Detection Recommendations
3-5 specific, actionable detection rules or checks security teams should implement this week.

## Sources
List the actual URLs you found information from.

---
*Auto-generated by [AI Threat Intel Tracker](https://github.com/Aleks1712/cybersecurity-labs/tree/main/ai-threat-intel) using Anthropic API with web search.*

IMPORTANT: Only include REAL incidents you find via search. If you find fewer than 3, that's fine. Quality over quantity. Never fabricate incidents."""

    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=4000,
        tools=[{"type": "web_search_20250305", "name": "web_search"}],
        messages=[{"role": "user", "content": prompt}]
    )

    # Extract text from response
    report_text = ""
    for block in response.content:
        if hasattr(block, "text"):
            report_text += block.text

    # If multi-turn needed (tool use), continue
    if response.stop_reason == "tool_use":
        messages = [
            {"role": "user", "content": prompt},
            {"role": "assistant", "content": response.content}
        ]
        # Process tool results
        tool_results = []
        for block in response.content:
            if block.type == "tool_use":
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": "Search completed. Please continue writing the report."
                })
        if tool_results:
            messages.append({"role": "user", "content": tool_results})
            followup = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=4000,
                tools=[{"type": "web_search_20250305", "name": "web_search"}],
                messages=messages
            )
            for block in followup.content:
                if hasattr(block, "text"):
                    report_text += block.text

    # Save report
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"reports/{date_str}-weekly-report.md"
    os.makedirs("ai-threat-intel/reports", exist_ok=True)
    filepath = f"ai-threat-intel/{filename}"

    with open(filepath, "w") as f:
        f.write(report_text)

    print(f"Report saved to {filepath}")
    print(f"Length: {len(report_text)} characters")

    # Update README with new report link
    readme_path = "ai-threat-intel/README.md"
    with open(readme_path, "r") as f:
        readme = f.read()

    new_row = f"| {date_str} | [Weekly Report](reports/{date_str}-weekly-report.md) |"
    readme = readme.replace(
        "| *Reports appear here automatically* | |",
        f"{new_row}\n| *Reports appear here automatically* | |"
    )

    with open(readme_path, "w") as f:
        f.write(readme)

    print("README updated with new report link")

if __name__ == "__main__":
    generate_report()
